name: Azure login
on: 
  workflow_dispatch:
    
jobs:
  login:
    runs-on: ubuntu-latest
    steps:
      - name: 'Az version'
        run: az version
      - name: 'Az login'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

