name: Azure login
on: 
  workflow_dispatch:
    
jobs:
  login:
    runs-on: ubuntu-latest
    steps:
      - name: 'Az version'
        run: az version
      - name: 'Az CLI Login'
        uses: azure/login@v1
        with: 
          inlineScript: |
            az login --identity

